[package]
name = "window_events"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.4"
windows = { version = "0.61.1", features = ["Win32_UI_Accessibility", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Threading"] }
